In [38]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [39]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values


In [40]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [41]:
print(y)

[1 0 1 ... 1 1 0]


In [42]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [43]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [44]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [47]:
ann = tf.keras.models.Sequential()

In [48]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [49]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [50]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [51]:
# compile the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [52]:
# train the ANN
ann.fit(X_train, y_train, batch_size=32, epochs=100)



Epoch 1/100
250/250 [==============================] - 1s 824us/step - loss: 0.6447 - accuracy: 0.6392
Epoch 2/100
250/250 [==============================] - 0s 783us/step - loss: 0.4857 - accuracy: 0.7970
Epoch 3/100
250/250 [==============================] - 0s 819us/step - loss: 0.4446 - accuracy: 0.8090
Epoch 4/100
250/250 [==============================] - 0s 791us/step - loss: 0.4239 - accuracy: 0.8198
Epoch 5/100
250/250 [==============================] - 0s 803us/step - loss: 0.4064 - accuracy: 0.8282
Epoch 6/100
250/250 [==============================] - 0s 751us/step - loss: 0.3896 - accuracy: 0.8365
Epoch 7/100
250/250 [==============================] - 0s 751us/step - loss: 0.3777 - accuracy: 0.8438
Epoch 8/100
250/250 [==============================] - 0s 723us/step - loss: 0.3702 - accuracy: 0.8436
Epoch 9/100
250/250 [==============================] - 0s 775us/step - loss: 0.3656 - accuracy: 0.8466
Epoch 10/100
250/250 [==============================] - 0s 727us/step - l

In [53]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 [==============================] - 0s 52ms/step
[[0.03270937]]


In [60]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

63/63 [==============================] - 0s 516us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [61]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.869

In [62]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1522   73]
 [ 189  216]]
